import IMovie from '@/models/IMovie';

export const genres = [
    'Артхаус',
    'Вестерн',
    'Для детей',
    'Зарубежные',
    'Комедии',
    'Мистические',
    'Приключения',
    'Советские',
    'Ужасы',
    'Биография',
    'Военные',
    'Документальные',
    'Исторические',
    'Криминал',
    'Музыкальные',
    'Русские',
    'Спорт',
    'Фантастика',
    'Боевики',
    'Детективы',
    'Драмы',
    'Катастрофы',
    'Мелодрамы',
    'По комиксам',
    'Семейные',
    'Триллеры',
    'Фэнтези',
];

export const countries = [
    'Австралия',
    'Аргентина',
    'Армения',
    'Беларусь',
    'Бельгия',
    'Бразилия',
    'Великобритания',
    'Венгрия',
    'Германия',
    'Гонконг',
    'Дания',
    'Индия',
    'Ирландия',
    'Испания',
    'Италия',
    'Казахстан',
    'Канада',
    'Китай',
    'Колумбия',
    'Мексика',
    'Нидерланды',
    'Новая Зеландия',
    'Норвегия',
    'Польша',
    'Россия',
    'СССР',
    'США',
    'Таиланд',
    'Турция',
    'Финляндия',
    'Франция',
    'Швейцария',
    'Швеция',
    'ЮАР',
    'Южная Корея',
    'Япония',
];

export const actorSuggestions = [
    {
        id: 71427,
        name: 'Франсуа Клюзе',
        enName: 'François Cluzet',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_71427.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 41644,
        name: 'Омар Си',
        enName: 'Omar Sy',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_41644.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 57174,
        name: 'Анн Ле Ни',
        enName: 'Anne Le Ny',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_57174.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 868557,
        name: 'Одри Флеро',
        enName: 'Audrey Fleurot',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_868557.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 541041,
        name: 'Жозефин де Мо',
        enName: 'Joséphine de Meaux',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_541041.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 445,
        name: 'Клотильд Молле',
        enName: 'Clotilde Mollet',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_445.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 964574,
        name: 'Альба Гайя Крагеде Беллуджи',
        enName: 'Alba Gaïa Bellugi',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_964574.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2237576,
        name: 'Сирил Менди',
        enName: 'Cyril Mendy',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2237576.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 3084679,
        name: 'Салимата Камате',
        enName: 'Salimata Kamate',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_3084679.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 3084680,
        name: 'Абса Дьяту Тур',
        enName: 'Absa Diatou Toure',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_3084680.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 83742,
        name: 'Грегуар Эстерманн',
        enName: 'Grégoire Oestermann',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_83742.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 233518,
        name: 'Доминик Дагье',
        enName: 'Dominique Daguier',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_233518.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 25264,
        name: 'Франсуа Карон',
        enName: 'François Caron',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_25264.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 5570,
        name: 'Кристиан Амери',
        enName: 'Christian Ameri',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_5570.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2497518,
        name: 'Тома Соливерес',
        enName: 'Thomas Solivérès',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2497518.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 240040,
        name: 'Дороти Бриер',
        enName: 'Dorothée Brière',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_240040.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 1960244,
        name: 'Мари-Лор Дикуру',
        enName: 'Marie-Laure Descoureaux',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_1960244.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 1283646,
        name: 'Эмили Кан',
        enName: 'Émilie Caen',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_1283646.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2216393,
        name: 'Сильвен Лазард',
        enName: 'Sylvain Lazard',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2216393.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2687585,
        name: 'Жан Франсуа Кэйри',
        enName: 'Jean-François Cayrey',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2687585.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2228474,
        name: 'Йен Фенелон',
        enName: 'Ian Fenelon',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2228474.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2200014,
        name: 'Рено Барсе',
        enName: 'Renaud Barse',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2200014.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 1617276,
        name: 'Франсуа Бюрелу',
        enName: 'François Bureloup',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_1617276.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 58912,
        name: 'Никки Марбо',
        enName: 'Nicky Marbot',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_58912.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 1277398,
        name: 'Бенжамин Барош',
        enName: 'Benjamin Baroche',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_1277398.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 1171108,
        name: 'Жером Паувельс',
        enName: 'Jérôme Pauwels',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_1171108.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 551535,
        name: 'Антуан Лоран',
        enName: 'Antoine Laurent',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_551535.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2224913,
        name: 'Фабрис Мантенья',
        enName: 'Fabrice Mantegna',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2224913.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2687586,
        name: 'Хеди Бушенафа',
        enName: 'Hedi Bouchenafa',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2687586.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 792895,
        name: 'Каролин Бург',
        enName: 'Caroline Bourg',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_792895.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 99326,
        name: 'Мишель Виноградов',
        enName: 'Michel Winogradoff',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_99326.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2687587,
        name: 'Кевин Вамо',
        enName: 'Kévin Wamo',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2687587.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2687588,
        name: 'Эллиот Латиль',
        enName: 'Elliot Latil',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2687588.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2687589,
        name: 'Ален Антони',
        enName: 'Alain Anthony',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2687589.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2687590,
        name: 'Доминик Анри',
        enName: 'Dominique Henry',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2687590.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 3084681,
        name: 'Ле Капариксьо Франсе',
        enName: 'Le Capriccio Français',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_3084681.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 3084682,
        name: 'Филипп Ле Февр',
        enName: 'Philippe Le Fevre',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_3084682.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2269034,
        name: 'Пьер-Лоран Барнерон',
        enName: 'Pierre-Laurent Barneron',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2269034.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 4559766,
        name: 'Хэ Юньпин',
        enName: 'He Yunping',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_4559766.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 3152842,
        name: 'Филипп Поццо ди Борго',
        enName: 'Philippe Pozzo di Borgo',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_3152842.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2789409,
        name: 'Абдель Селлу',
        enName: 'Abdel Sellou',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2789409.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 797,
        name: 'Мэттью МакКонахи',
        enName: 'Matthew McConaughey',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_797.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 2,
    },
    {
        id: 38702,
        name: 'Чарли Ханнэм',
        enName: 'Charlie Hunnam',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_38702.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 4950097,
        name: 'Генри Голдинг',
        enName: 'Henry Golding',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_4950097.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 8090,
        name: 'Хью Грант',
        enName: 'Hugh Grant',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_8090.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 1067193,
        name: 'Мишель Докери',
        enName: 'Michelle Dockery',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_1067193.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 1146480,
        name: 'Джереми Стронг',
        enName: 'Jeremy Strong',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_1146480.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2444,
        name: 'Эдди Марсан',
        enName: 'Eddie Marsan',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2444.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 2,
    },
    {
        id: 2454111,
        name: 'Джейсон Вонг',
        enName: 'Jason Wong',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2454111.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 2,
    },
    {
        id: 373,
        name: 'Колин Фаррелл',
        enName: 'Colin Farrell',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_373.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 1006787,
        name: 'Лин Рене',
        enName: 'Lyne Renée',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_1006787.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 2,
    },
    {
        id: 25964,
        name: 'Том У',
        enName: 'Tom Wu',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_25964.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 3002651,
        name: 'Чиди Аджуфо',
        enName: 'Chidi Ajufo',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_3002651.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 5968202,
        name: 'Саймон Р. Баркер',
        enName: 'Simon R. Barker',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_5968202.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 1850607,
        name: 'Джон Даглиш',
        enName: 'John Dagleish',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_1850607.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 4717127,
        name: 'Джордан Лонг',
        enName: 'Jordan Long',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_4717127.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 3393000,
        name: 'Лили Фрайзер',
        enName: 'Lily Frazer',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_3393000.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 3300883,
        name: 'Гершвин Эсташ мл.',
        enName: 'Gershwyn Eustache Jnr',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_3300883.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 13177,
        name: 'Сэмюэл Уэст',
        enName: 'Samuel West',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_13177.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 40828,
        name: 'Джеральдин Сомервилль',
        enName: 'Geraldine Somerville',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_40828.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 4679,
        name: 'Элиот Самнер',
        enName: 'Eliot Sumner',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_4679.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 1308171,
        name: 'Франц Драмех',
        enName: 'Franz Drameh',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_1308171.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 4653501,
        name: 'Кристофер Эвангелу',
        enName: 'Christopher Evangelou',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_4653501.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 23879,
        name: 'Джим Уоррен',
        enName: 'James Warren',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_23879.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 2,
    },
    {
        id: 2817170,
        name: 'Шон Сагар',
        enName: 'Sean Sagar',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2817170.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 5931690,
        name: 'Багзи Мэлоун',
        enName: 'Bugzy Malone',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_5931690.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2317698,
        name: 'Том Рис Харрис',
        enName: 'Tom Rhys Harries',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2317698.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 5325577,
        name: 'Дэнни Гриффин',
        enName: 'Danny Griffin',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_5325577.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 1575352,
        name: 'Макс Беннетт',
        enName: 'Max Bennett',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_1575352.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2497432,
        name: 'Евгения Кузьмина',
        enName: 'Eugenia Kuzmina',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2497432.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 3034185,
        name: 'Брюс Чон',
        enName: 'Bruce Chong',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_3034185.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 687946,
        name: 'Эшли Макгуайр',
        enName: 'Ashley McGuire',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_687946.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 34921,
        name: 'Джордж Эспри',
        enName: 'George Asprey',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_34921.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },

    {
        id: 4787983,
        name: 'Джек Джонс',
        enName: 'Jack Jones',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_4787983.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 2442849,
        name: 'Сэмми Уильямс',
        enName: 'Sammy Williams',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2442849.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 588830,
        name: 'Гай Лист',
        enName: 'Guy List',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_588830.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 1,
    },
    {
        id: 41834,
        name: 'Марвин Кэмпбелл',
        enName: 'Marvin Campbell',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_41834.jpg',
        profession: ['актеры'],
        enProfession: ['actor'],
        countMovies: 2,
    },
];
export const directorSuggestions = [
    {
        id: 382906,
        name: 'Оливье Накаш',
        enName: 'Olivier Nakache',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_382906.jpg',
        profession: ['режиссеры'],
        enProfession: ['director'],
        countMovies: 1,
    },
    {
        id: 426346,
        name: 'Эрик Толедано',
        enName: 'Éric Toledano',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_426346.jpg',
        profession: ['режиссеры'],
        enProfession: ['director'],
        countMovies: 1,
    },
    {
        id: 45159,
        name: 'Гай Ричи',
        enName: 'Guy Ritchie',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_45159.jpg',
        profession: ['режиссеры'],
        enProfession: ['director'],
        countMovies: 2,
    },
    {
        id: 10988,
        name: 'Мартин Скорсезе',
        enName: 'Martin Scorsese',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_10988.jpg',
        profession: ['режиссеры'],
        enProfession: ['director'],
        countMovies: 1,
    },

    {
        id: 24817,
        name: 'Крис Коламбус',
        enName: 'Chris Columbus',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_24817.jpg',
        profession: ['режиссеры'],
        enProfession: ['director'],
        countMovies: 1,
    },
    {
        id: 27977,
        name: 'Джеймс Кэмерон',
        enName: 'James Cameron',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_27977.jpg',
        profession: ['режиссеры'],
        enProfession: ['director'],
        countMovies: 1,
    },
    {
        id: 24262,
        name: 'Фрэнк Дарабонт',
        enName: 'Frank Darabont',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_24262.jpg',
        profession: ['режиссеры'],
        enProfession: ['director'],
        countMovies: 1,
    },
    {
        id: 41477,
        name: 'Кристофер Нолан',
        enName: 'Christopher Nolan',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_41477.jpg',
        profession: ['режиссеры'],
        enProfession: ['director'],
        countMovies: 1,
    },
    {
        id: 1562107,
        name: 'Байрон Ховард',
        enName: 'Byron Howard',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_1562107.jpg',
        profession: ['режиссеры'],
        enProfession: ['director'],
        countMovies: 1,
    },
    {
        id: 280500,
        name: 'Рич Мур',
        enName: 'Rich Moore',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_280500.jpg',
        profession: ['режиссеры'],
        enProfession: ['director'],
        countMovies: 1,
    },
    {
        id: 2427806,
        name: 'Джаред Буш',
        enName: 'Jared Bush',
        photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2427806.jpg',
        profession: ['режиссеры'],
        enProfession: ['director'],
        countMovies: 1,
    },
];

export const movieTest: IMovie = {
    id: 535341,
    type: 'movie',
    name: '1+1',
    enName: 'Intouchables',
    posterUrl: require('./img/BG554460.jpg'),
    posterPreviewURL: require('./img/BG554460.jpg'),
    year: 2011,
    description:
        'Пострадав в результате несчастного случая, богатый аристократ Филипп нанимает в помощники человека, который менее всего подходит для этой работы, – молодого жителя предместья Дрисса, только что освободившегося из тюрьмы. Несмотря на то, что Филипп прикован к инвалидному креслу, Дриссу удается привнести в размеренную жизнь аристократа дух приключений.',
    shortDescription:
        'Аристократ на коляске нанимает в сиделки бывшего заключенного. Искрометная французская комедия с Омаром Си',
    ageRating: 16,
    ratingKp: 8.805,
    votesKp: 1580297,
    movieLength: 112,
    genres: [
        {
            id: 1,
            name: 'драма',
            enName: 'drama',
        },
        {
            id: 2,
            name: 'комедия',
            enName: 'comedy',
        },
        {
            id: 3,
            name: 'биография',
            enName: 'biography',
        },
    ],
    countries: [
        {
            id: 1,
            name: 'Франция',
            enName: 'France',
        },
    ],
    persons: [
        {
            id: 71427,
            name: 'Франсуа Клюзе',
            enName: 'François Cluzet',
            photo: require('./img/BG554460.jpg'),
            profession: ['актеры'],
            enProfession: ['actor'],
            countMovies: 1,
        },
        {
            id: 3084680,
            name: 'Абса Дьяту Тур',
            enName: 'Absa Diatou Toure',
            photo: require('./img/BG554460.jpg'),
            profession: ['актеры'],
            enProfession: ['actor'],
            countMovies: 1,
        },
        {
            id: 1960244,
            name: 'Мари-Лор Дикуру',
            enName: 'Marie-Laure Descoureaux',
            photo: require('./img/BG554460.jpg'),
            profession: ['актеры'],
            enProfession: ['actor'],
            countMovies: 1,
        },
        {
            id: 2228474,
            name: 'Йен Фенелон',
            enName: 'Ian Fenelon',
            photo: require('./img/BG554460.jpg'),
            profession: ['актеры'],
            enProfession: ['actor'],
            countMovies: 1,
        },
        {
            id: 1277398,
            name: 'Бенжамин Барош',
            enName: 'Benjamin Baroche',
            photo: require('./img/BG554460.jpg'),
            profession: ['актеры'],
            enProfession: ['actor'],
            countMovies: 1,
        },
        {
            id: 1171108,
            name: 'Жером Паувельс',
            enName: 'Jérôme Pauwels',
            photo: require('./img/BG554460.jpg'),
            profession: ['актеры'],
            enProfession: ['actor'],
            countMovies: 1,
        },
        {
            id: 551535,
            name: 'Антуан Лоран',
            enName: 'Antoine Laurent',
            photo: require('./img/BG554460.jpg'),
            profession: ['актеры'],
            enProfession: ['actor'],
            countMovies: 1,
        },
        {
            id: 2687590,
            name: 'Доминик Анри',
            enName: 'Dominique Henry',
            photo: require('./img/BG554460.jpg'),
            profession: ['актеры'],
            enProfession: ['actor'],
            countMovies: 1,
        },
        {
            id: 3084681,
            name: 'Ле Капариксьо Франсе',
            enName: 'Le Capriccio Français',
            photo: require('./img/BG554460.jpg'),
            profession: ['актеры'],
            enProfession: ['actor'],
            countMovies: 1,
        },
        {
            id: 3084682,
            name: 'Филипп Ле Февр',
            enName: 'Philippe Le Fevre',
            photo: require('./img/BG554460.jpg'),
            profession: ['актеры'],
            enProfession: ['actor'],
            countMovies: 1,
        },
        {
            id: 2269034,
            name: 'Пьер-Лоран Барнерон',
            enName: 'Pierre-Laurent Barneron',
            photo: require('./img/BG554460.jpg'),
            profession: ['актеры'],
            enProfession: ['actor'],
            countMovies: 1,
        },
        {
            id: 4559766,
            name: 'Хэ Юньпин',
            enName: 'He Yunping',
            photo: require('./img/BG554460.jpg'),
            profession: ['актеры'],
            enProfession: ['actor'],
            countMovies: 1,
        },
        {
            id: 3152842,
            name: 'Филипп Поццо ди Борго',
            enName: 'Philippe Pozzo di Borgo',
            photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_3152842.jpg',
            profession: ['актеры', 'редакторы'],
            enProfession: ['actor', 'writer'],
            countMovies: 1,
        },
        {
            id: 2789409,
            name: 'Абдель Селлу',
            enName: 'Abdel Sellou',
            photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2789409.jpg',
            profession: ['актеры'],
            enProfession: ['actor'],
            countMovies: 1,
        },
        {
            id: 590648,
            name: 'Людовико Эйнауди',
            enName: 'Ludovico Einaudi',
            photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_590648.jpg',
            profession: ['композиторы'],
            enProfession: ['composer'],
            countMovies: 1,
        },
        {
            id: 634036,
            name: 'Матьё Вадпьед',
            enName: 'Mathieu Vadepied',
            photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_634036.jpg',
            profession: ['художники', 'операторы'],
            enProfession: ['designer', 'operator'],
            countMovies: 1,
        },
        {
            id: 1998619,
            name: 'Изабель Паннетье',
            enName: 'Isabelle Pannetier',
            photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_1998619.jpg',
            profession: ['художники'],
            enProfession: ['designer'],
            countMovies: 1,
        },
        {
            id: 2004628,
            name: 'Оливия Блох-Лене',
            enName: 'Olivia Bloch-Lainé',
            photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2004628.jpg',
            profession: ['художники'],
            enProfession: ['designer'],
            countMovies: 1,
        },
        {
            id: 382906,
            name: 'Оливье Накаш',
            enName: 'Olivier Nakache',
            photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_382906.jpg',
            profession: ['режиссеры', 'редакторы'],
            enProfession: ['director', 'writer'],
            countMovies: 1,
        },
        {
            id: 426346,
            name: 'Эрик Толедано',
            enName: 'Éric Toledano',
            photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_426346.jpg',
            profession: ['режиссеры', 'редакторы'],
            enProfession: ['director', 'writer'],
            countMovies: 1,
        },
        {
            id: 1987674,
            name: 'Дориан Ригаль-Ансу',
            enName: 'Dorian Rigal-Ansous',
            photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_1987674.jpg',
            profession: ['монтажеры'],
            enProfession: ['editor'],
            countMovies: 1,
        },
        {
            id: 2402288,
            name: 'Арно Бертран',
            enName: 'Arnaud Bertrand',
            photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_2402288.jpg',
            profession: ['продюсеры'],
            enProfession: ['producer'],
            countMovies: 1,
        },
        {
            id: 884847,
            name: 'Доминик Бутонна',
            enName: 'Dominique Boutonnat',
            photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_884847.jpg',
            profession: ['продюсеры'],
            enProfession: ['producer'],
            countMovies: 1,
        },
        {
            id: 1963412,
            name: 'Данил Щебланов',
            enName: '',
            photo: 'https://st.kp.yandex.net/images/actor_iphone/iphone360_1963412.jpg',
            profession: ['актеры дубляжа'],
            enProfession: ['voice_actor'],
            countMovies: 1,
        },
    ],
    trailer: 'https://www.youtube.com/embed/0RqDiYnFxTk',
    watchingWithMovie: [],
    comments: [],
};

export const moviesTest = [
    {
        id: 535341,
        name: '1+1',
        enName: 'Intouchables',
        posterPreviewURL: 'https://st.kp.yandex.net/images/film_iphone/iphone360_535341.jpg',
        premiereRussia: '2012-04-26T00:00:00.000Z',
        hasIMAX: false,
        year: 2011,
        ageRating: 16,
        ratingKp: 8.805,
        votesKp: 1580297,
        movieLength: 112,
        genres: [
            {
                id: 1,
                name: 'драма',
                enName: 'drama',
            },
            {
                id: 2,
                name: 'комедия',
                enName: 'comedy',
            },
            {
                id: 3,
                name: 'биография',
                enName: 'biography',
            },
        ],
        countries: [
            {
                id: 1,
                name: 'Франция',
                enName: 'France',
            },
        ],
    },
    {
        id: 1143242,
        name: 'Джентльмены',
        enName: 'The Gentlemen',
        posterPreviewURL: 'https://st.kp.yandex.net/images/film_iphone/iphone360_1143242.jpg',
        premiereRussia: '2020-02-13T00:00:00.000Z',
        hasIMAX: true,
        year: 2019,
        ageRating: 18,
        ratingKp: 8.548,
        votesKp: 1398268,
        movieLength: 113,
        genres: [
            {
                id: 4,
                name: 'криминал',
                enName: 'crime',
            },
            {
                id: 2,
                name: 'комедия',
                enName: 'comedy',
            },
            {
                id: 5,
                name: 'боевик',
                enName: 'action',
            },
        ],
        countries: [
            {
                id: 2,
                name: 'Великобритания',
                enName: 'Great Britain',
            },
            {
                id: 3,
                name: 'США',
                enName: 'USA',
            },
        ],
    },
    {
        id: 462682,
        name: 'Волк с Уолл-стрит',
        enName: 'The Wolf of Wall Street',
        posterPreviewURL: 'https://st.kp.yandex.net/images/film_iphone/iphone360_462682.jpg',
        premiereRussia: '2014-02-06T00:00:00.000Z',
        hasIMAX: false,
        year: 2013,
        ageRating: 18,
        ratingKp: 7.972,
        votesKp: 1113124,
        movieLength: 180,
        genres: [
            {
                id: 1,
                name: 'драма',
                enName: 'drama',
            },
            {
                id: 4,
                name: 'криминал',
                enName: 'crime',
            },
            {
                id: 3,
                name: 'биография',
                enName: 'biography',
            },
            {
                id: 2,
                name: 'комедия',
                enName: 'comedy',
            },
        ],
        countries: [
            {
                id: 3,
                name: 'США',
                enName: 'USA',
            },
        ],
    },
    {
        id: 251733,
        name: 'Аватар',
        enName: 'Avatar',
        posterPreviewURL: 'https://st.kp.yandex.net/images/film_iphone/iphone360_251733.jpg',
        premiereRussia: '2009-12-17T00:00:00.000Z',
        hasIMAX: true,
        year: 2009,
        ageRating: 12,
        ratingKp: 7.971,
        votesKp: 976171,
        movieLength: 162,
        genres: [
            {
                id: 8,
                name: 'фантастика',
                enName: 'fantasy',
            },
            {
                id: 5,
                name: 'боевик',
                enName: 'action',
            },
            {
                id: 1,
                name: 'драма',
                enName: 'drama',
            },
            {
                id: 9,
                name: 'приключения',
                enName: 'adventures',
            },
        ],
        countries: [
            {
                id: 3,
                name: 'США',
                enName: 'USA',
            },
        ],
    },
    {
        id: 41520,
        name: 'Брат 2',
        enName: '',
        posterPreviewURL: 'https://st.kp.yandex.net/images/film_iphone/iphone360_41520.jpg',
        premiereRussia: '2000-05-11T00:00:00.000Z',
        hasIMAX: false,
        year: 2000,
        ageRating: 16,
        ratingKp: 8.181,
        votesKp: 846177,
        movieLength: 127,
        genres: [
            {
                id: 5,
                name: 'боевик',
                enName: 'action',
            },
            {
                id: 4,
                name: 'криминал',
                enName: 'crime',
            },
        ],
        countries: [
            {
                id: 4,
                name: 'Россия',
                enName: 'Russia',
            },
        ],
    },
];

export const promoMovieTest = {
    id: 1,
    type: '',
    name: 'сыщицы',
    enName: '',
    posterUrl: 'https://thumbs.dfs.ivi.ru/storage33/contents/e/a/29d4105d2daaddc1591c6542d0571f.jpg/1216x524/?q=85',
    posterPreviewURL: '',
    logo: 'https://thumbs.dfs.ivi.ru/storage33/contents/1/3/99035f529d7c175424b1c905d36462.png/x200/',
    year: 2023,
    description: '',
    shortDescription: 'Яркая сыщица и тихоня-учёная должны объединить усилия, чтобы раскрыть запутанное дело',
    shortDescriptionEn: 'A striking detective and a timid scientist must team up to solve a complicated case',
    ageRating: 18,
    ratingKp: 8,
    votesKp: 1000,
    movieLength: 120,
    genres: [],
    countries: [],
    persons: [],
    trailer: '',
    watchingWithMovie: [],
    comments: [],
};

export const ratingMovieTest = {
    id: 1,
    type: '',
    name: 'зимородок',
    enName: '',
    posterUrl: 'https://thumbs.dfs.ivi.ru/storage6/contents/e/0/08c76a2df45108ec28af6300cc5b93.jpg/304x620//?q=85',
    posterPreviewURL: '',
    logo: 'https://thumbs.dfs.ivi.ru/storage4/contents/b/3/826ab6a9a975f9919837f0d17ba642.png/x200/?q=85',
    year: 2023,
    description: '',
    shortDescription: '',
    ageRating: 18,
    ratingKp: 8,
    votesKp: 1000,
    movieLength: 120,
    genres: [],
    countries: [],
    persons: [],
    place: 1,
    trailer: '',
    watchingWithMovie: [],
    comments: [],
};

export const genersTest = [
    {
        id: 1,
        name: 'драма',
        enName: 'drama',
    },
    {
        id: 2,
        name: 'комедия',
        enName: 'comedy',
    },
    {
        id: 3,
        name: 'биография',
        enName: 'biography',
    },
    {
        id: 4,
        name: 'криминал',
        enName: 'crime',
    },
    {
        id: 5,
        name: 'боевик',
        enName: 'action',
    },
    {
        id: 9,
        name: 'приключения',
        enName: 'adventures',
    },
];

export const countriesTest = [
    {
        id: 1,
        name: 'Франция',
        enName: 'France',
    },
    {
        id: 2,
        name: 'Великобритания',
        enName: 'Great Britain',
    },
    {
        id: 3,
        name: 'США',
        enName: 'USA',
    },
    {
        id: 4,
        name: 'Россия',
        enName: 'Russia',
    },
    {
        id: 5,
        name: 'СССР',
        enName: 'USSR',
    },
    {
        id: 6,
        name: 'Канада',
        enName: 'Canada',
    },
];

export const commentsTest = [
    {
        id: 1,
        user: 'Slater',
        movieid: 1,
        date: 'Sat Jun 10 2023 15:33:19 GMT+0700 (Красноярск, стандартное время)',
        text: 'Великий Эверест пытаются покорить многие. Зачем? Как по мне в этом нет смысла. Но все люди разные, именно о тех, кто готов рискнуть и достигнуть поставленной цели фильм и повествует. И он на реальных событиях. Фильм хороший, но не стоит вдохновляться. Не все пройдет гладко при подъеме. В фильме хорошо показаны глупости людей, амбиции вразрез разуму, и беспомощность перед силой природы.',
        childComment: [
            {
                id: 4,
                user: 'Игорь',
                movieid: 1,
                date: 'Sat Jun 11 2023 15:33:19 GMT+0700 (Красноярск, стандартное время)',
                text: 'Ты прав!',
            },
            {
                id: 5,
                user: 'Гость',
                movieid: 1,
                date: 'Sat Jun 11 2023 15:33:19 GMT+0700 (Красноярск, стандартное время)',
                text: 'Точно',
            },
        ],
    },
    {
        id: 2,
        user: 'lanaalmaty',
        movieid: 1,
        date: 'Sat Jun 10 2023 15:33:19 GMT+0700 (Красноярск, стандартное время)',
        text: 'Фильм классный! Но здесь все забыли главного героя. Анатолия Букреева. Ведь он свою группу все таки вывел из бури и все живы!',
        childComment: [],
    },
];
