import IMovie from '@/models/IMovie';

export interface IMoviePromo extends IMovie {
    shortDescriptionEn?: string;
    logo?: string;
}

export const promoMovies: IMoviePromo[] = [
    {
        id: 1,
        type: '',
        name: 'сыщицы',
        enName: '',
        posterUrl: 'https://thumbs.dfs.ivi.ru/storage33/contents/e/a/29d4105d2daaddc1591c6542d0571f.jpg/1216x524/?q=85',
        posterPreviewURL: '',
        logo: 'https://thumbs.dfs.ivi.ru/storage33/contents/1/3/99035f529d7c175424b1c905d36462.png/x200/',
        year: 2023,
        description: '',
        shortDescription: 'Яркая сыщица и тихоня-учёная должны объединить усилия, чтобы раскрыть запутанное дело',
        shortDescriptionEn: 'A striking detective and a timid scientist must team up to solve a complicated case',
        ageRating: 18,
        ratingKp: 8,
        votesKp: 1000,
        movieLength: 120,
        genres: [],
        countries: [],
        persons: [],
        trailer: '',
        watchingWithMovie: [],
        comments: [],
    },
    {
        id: 1,
        type: '',
        name: 'операция фортуна',
        enName: '',
        posterUrl: 'https://thumbs.dfs.ivi.ru/storage38/contents/3/1/e5d84280c3ab43434b3851803326c6.jpg/1216x524/?q=85',
        posterPreviewURL: '',
        logo: 'https://thumbs.dfs.ivi.ru/storage9/contents/0/7/c29756fa4d94a6ba334836e7820b3a.png/x200/',
        year: 2023,
        description: '',
        shortDescription:
            'Ваши любимые Джейсон Стэйтем и Хью Грант спасают мир в шпионской комедии вашего любимого Гая Ричи',
        shortDescriptionEn:
            'Your favourite Jason Statham and Hugh Grant save the world in a spy comedy by your favourite Guy Ritchie',
        ageRating: 18,
        ratingKp: 8,
        votesKp: 1000,
        movieLength: 120,
        genres: [],
        countries: [],
        persons: [],
        trailer: '',
        watchingWithMovie: [],
        comments: [],
    },
    {
        id: 1,
        type: '',
        name: 'сын',
        enName: '',
        posterUrl: 'https://thumbs.dfs.ivi.ru/storage8/contents/e/6/1c818185872cebbf9b6bb3b411d645.jpg/1216x524/?q=85',
        posterPreviewURL: '',
        logo: 'https://thumbs.dfs.ivi.ru/storage6/contents/d/b/82ec0ca76b26978843a3a0ed2afcdc.png/x200/',
        year: 2023,
        description: '',
        shortDescription:
            'Успешный юрист пытается спасти сына у опасной черты. Хью Джекман в мощной драме от режиссёра «Отца»',
        shortDescriptionEn:
            'A successful lawyer is trying to save his son from crossing a dangerous line. Hugh Jackman in a powerful drama from the director of The Father',
        ageRating: 18,
        ratingKp: 8,
        votesKp: 1000,
        movieLength: 120,
        genres: [],
        countries: [],
        persons: [],
        trailer: '',
        watchingWithMovie: [],
        comments: [],
    },
    {
        id: 1,
        type: '',
        name: 'сожги все мои письма',
        enName: '',
        posterUrl: 'https://thumbs.dfs.ivi.ru/storage4/contents/9/9/9d75f48674c5fa09aa248890e58277.jpg/1216x524/?q=85',
        posterPreviewURL: '',
        logo: 'https://thumbs.dfs.ivi.ru/storage8/contents/0/d/a8ef45616c51b3af3602c80fd2fc4e.png/x200/',
        year: 2023,
        description: '',
        shortDescription:
            'Литератор Алекс пытается разобраться в прошлом своей семьи. Историческая драма с Биллом Скарсгардом',
        shortDescriptionEn: 'Writer Alex is delving into the past of his family. Historical drama with Bill Skarsgard',
        ageRating: 18,
        ratingKp: 8,
        votesKp: 1000,
        movieLength: 120,
        genres: [],
        countries: [],
        persons: [],
        trailer: '',
        watchingWithMovie: [],
        comments: [],
    },
];
