import IMovie from '@/models/IMovie';

export interface IMoviePromo extends IMovie {
    shortDescriptionEn?: string;
    logo?: string;
}

export const promoMovies: IMoviePromo[] = [
    {
        id: 1405508,
        type: '',
        name: 'операция фортуна',
        enName: '',
        posterUrl: 'https://thumbs.dfs.ivi.ru/storage38/contents/3/1/e5d84280c3ab43434b3851803326c6.jpg/1216x524/?q=85',
        posterPreviewURL: '',
        logo: 'https://thumbs.dfs.ivi.ru/storage9/contents/0/7/c29756fa4d94a6ba334836e7820b3a.png/x200/',
        year: 2023,
        description: '',
        shortDescription:
            'Ваши любимые Джейсон Стэйтем и Хью Грант спасают мир в шпионской комедии вашего любимого Гая Ричи',
        shortDescriptionEn:
            'Your favourite Jason Statham and Hugh Grant save the world in a spy comedy by your favourite Guy Ritchie',
        ageRating: 18,
        ratingKp: 8,
        votesKp: 1000,
        movieLength: 120,
        genres: [],
        countries: [],
        persons: [],
        trailer: '',
        watchingWithMovie: [],
        comments: [],
    },
    {
        id: 5129252,
        type: '',
        name: 'беспринципные в деревне',
        enName: '',
        posterUrl: 'https://thumbs.dfs.ivi.ru/storage28/contents/7/3/311c6a4093803c950d1153b674e3d7.jpg/1216x524/?q=85',
        posterPreviewURL: '',
        logo: 'https://thumbs.dfs.ivi.ru/storage33/contents/c/6/ebb1f750328adf266b9d867e6ce2d2.png/x200/',
        year: 2023,
        description: '',
        shortDescription: 'Столичные богачи учатся выживать в деревне. Продолжение хитового сериала с россыпью звёзд',
        shortDescriptionEn: 'Wealthy people of the capital are learning to survive in the countryside. A sequel to the hit TV show with a variety of movie',
        ageRating: 18,
        ratingKp: 8,
        votesKp: 1000,
        movieLength: 120,
        genres: [],
        countries: [],
        persons: [],
        trailer: '',
        watchingWithMovie: [],
        comments: [],
    },
    {
        id: 1225587,
        type: '',
        name: 'Серебряные коньки',
        enName: '',
        posterUrl: '	https://thumbs.dfs.ivi.ru/storage28/contents/2/7/2459ef29902894e72bb39fea6f8fbf.jpg/1216x524/?q=85',
        posterPreviewURL: '',
        logo: 'https://thumbs.dfs.ivi.ru/storage33/contents/4/b/ffa42c79f32340c5c773e34d187926.png/x200/',
        year: 2023,
        description: '',
        shortDescription:
            'Сын фонарщика и дочь чиновника идут навстречу мечте в сказочном Петербурге 1899 года',
        shortDescriptionEn: 'The son of a lamp lighter and the daughter of a civil servant are chasing their dream in a fabulous St. Petersburg of 1899',
        ageRating: 18,
        ratingKp: 8,
        votesKp: 1000,
        movieLength: 120,
        genres: [],
        countries: [],
        persons: [],
        trailer: '',
        watchingWithMovie: [],
        comments: [],
    },
    {
        id: 1001,
        type: '',
        name: 'сын',
        enName: '',
        posterUrl: 'https://thumbs.dfs.ivi.ru/storage8/contents/e/6/1c818185872cebbf9b6bb3b411d645.jpg/1216x524/?q=85',
        posterPreviewURL: '',
        logo: 'https://thumbs.dfs.ivi.ru/storage6/contents/d/b/82ec0ca76b26978843a3a0ed2afcdc.png/x200/',
        year: 2023,
        description: '',
        shortDescription:
            'Успешный юрист пытается спасти сына у опасной черты. Хью Джекман в мощной драме от режиссёра «Отца»',
        shortDescriptionEn:
            'A successful lawyer is trying to save his son from crossing a dangerous line. Hugh Jackman in a powerful drama from the director of The Father',
        ageRating: 18,
        ratingKp: 8,
        votesKp: 1000,
        movieLength: 120,
        genres: [],
        countries: [],
        persons: [],
        trailer: '',
        watchingWithMovie: [],
        comments: [],
    },
    {
        id: 1001,
        type: '',
        name: 'сожги все мои письма',
        enName: '',
        posterUrl: 'https://thumbs.dfs.ivi.ru/storage4/contents/9/9/9d75f48674c5fa09aa248890e58277.jpg/1216x524/?q=85',
        posterPreviewURL: '',
        logo: 'https://thumbs.dfs.ivi.ru/storage8/contents/0/d/a8ef45616c51b3af3602c80fd2fc4e.png/x200/',
        year: 2023,
        description: '',
        shortDescription:
            'Литератор Алекс пытается разобраться в прошлом своей семьи. Историческая драма с Биллом Скарсгардом',
        shortDescriptionEn: 'Writer Alex is delving into the past of his family. Historical drama with Bill Skarsgard',
        ageRating: 18,
        ratingKp: 8,
        votesKp: 1000,
        movieLength: 120,
        genres: [],
        countries: [],
        persons: [],
        trailer: '',
        watchingWithMovie: [],
        comments: [],
    },
];
