import { IActor } from './IActor';

export const actors: IActor[] = [
  {
    id: 1,
    img: '/img/actorTest1.jpg',
    amtMovies: 1,
    firstName: 'Рупертgggg',
    lastName: 'Гринтgggg',
    role: 'актерg',
  },
  {
    id: 2,
    img: '/img/actorTest2.jpg',
    amtMovies: 2,
    firstName: 'Том',
    lastName: 'Фелтон',
    role: 'актер',
  },
  {
    id: 3,
    img: '/img/actorTest1.jpg',
    amtMovies: 3,
    firstName: 'Руперт1',
    lastName: 'Гринт1',
    role: 'актер',
  },
  {
    id: 4,
    img: '/img/actorTest2.jpg',
    amtMovies: 4,
    firstName: 'Том1',
    lastName: 'Фелтон1',
    role: 'актер',
  },
  {
    id: 5,
    img: '/img/actorTest1.jpg',
    amtMovies: 5,
    firstName: 'Руперт2',
    lastName: 'Гринт2',
    role: 'актер',
  },
  {
    id: 6,
    img: '/img/actorTest2.jpg',
    amtMovies: 6,
    firstName: 'Том2',
    lastName: 'Фелтон2',
    role: 'актер',
  },
  {
    id: 7,
    img: '/img/actorTest1.jpg',
    amtMovies: 47,
    firstName: 'Руперт3',
    lastName: 'Гринт3',
    role: 'актер',
  },
  {
    id: 8,
    img: '/img/actorTest2.jpg',
    amtMovies: 11,
    firstName: 'Том3',
    lastName: 'Фелтон3',
    role: 'актер',
  },
  {
    id: 9,
    img: '/img/actorTest1.jpg',
    amtMovies: 4,
    firstName: 'Руперт4',
    lastName: 'Гринт4',
    role: 'актер',
  },
  {
    id: 10,
    img: '/img/actorTest2.jpg',
    amtMovies: 15,
    firstName: 'Том4',
    lastName: 'Фелтон4',
    role: 'актер',
  },
  {
    id: 11,
    img: '/img/actorTest1.jpg',
    amtMovies: 56,
    firstName: 'Руперт5',
    lastName: 'Гринт5',
    role: 'актер',
  },
  {
    id: 12,
    img: '/img/actorTest2.jpg',
    amtMovies: 24,
    firstName: 'Том5',
    lastName: 'Фелтон5',
    role: 'актер',
  },
  {
    id: 13,
    img: '/img/actorTest1.jpg',
    amtMovies: 13,
    firstName: 'Руперт6',
    lastName: 'Гринт6',
    role: 'актер',
  },
  {
    id: 14,
    img: '/img/actorTest2.jpg',
    amtMovies: 10,
    firstName: 'Том6',
    lastName: 'Фелтон6',
    role: 'актер',
  },
  {
    id: 15,
    img: '/img/actorTest1.jpg',
    amtMovies: 4,
    firstName: 'Рупертfffffffffffffffffffffffffffff7',
    lastName: 'Гринт7',
    role: 'актер',
  },
  {
    id: 16,
    img: '/img/actorTest2.jpg',
    amtMovies: 24,
    firstName: 'Том7',
    lastName: 'Фелтон7',
    role: 'актер',
  },
];
